# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CalcCoords
                                 A QGIS plugin
 Realiza la conversion de coordenadas en grados, minitos y segundos a grados decimales y tambien a coordenadas UTM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-04-19
        copyright            : (C) 2021 by Kevin Irias
        email                : kevin.irias.47@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CalcCoords class from file CalcCoords.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .calccoords import CalcCoords
    return CalcCoords(iface)
